# Generated by Django 3.0.2 on 2020-02-01 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_auto_20200201_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='seats',
        ),
        migrations.AddField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theaters.Theater'),
            preserve_default=False,
        ),
    ]
