# Generated by Django 3.0.2 on 2020-02-01 10:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('theaters', '0003_auto_20200201_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theater',
            new_name='Screen',
        ),
    ]
